#!/usr/bin/env zsh
# Homebrew Bundle

BREWFILE="${DOTFILES}/Brewfile"
# alias bbundle="brew bundle --file=$DOTFILES/Brewfile"
#
# # Create a Brewfile from all the currently installed Homebrew packages. Add --force to overwrite an existing Brewfile
# alias bbundledump="brew bundle dump --file=$DOTFILES/Brewfile"

echo 'Do you want to:'
echo "*Install* apps listed in $BREWFILE (default), or"
echo "*Update/Create* the Brewfile based on your current apps, or"
echo "*Show* Brewfile"
echo "*Bail*"
echo ""

OPTIONS=(Install Update/Create Show Bail)

select OPTION in "${OPTIONS[@]}"; do
  break
done

if [[ $OPTION == "Bail" ]]; then
  echo "${OPTION}"
  echo 'Okay. Bailing…'
elif [[ $OPTION == "Show" ]]; then
  echo "Showing ${BREWFILE} …"
  command cat "${BREWFILE}"
elif [[ $OPTION == "Update/Create" ]]; then
  echo "Running brew bundle dump --force --file=${BREWFILE} …"
  brew bundle dump --force --file="${BREWFILE}"
else
  echo "Running brew bundle --file=${BREWFILE} …"
  brew bundle --file="${BREWFILE}"
fi
