#!/usr/bin/env zsh

# Touch, make executable, and start editing a new script.
# newscript my_new_script.sh
function newscript() {
  local default_ext="js"
  local scriptdir filename ext editor userscript

  if [[ $# -eq 0 ]]; then
    print -r -- "newscript: touch, make executable and start editing a new script."
    print -u2 -- "\033[31;1mError:\033[0m Missing filename"
    print -r -- ""
    print -r -- "Usage: newscript SCRIPT_NAME.ext [directory]"
    return 1
  fi

  scriptdir="${2:-}"
  if [[ -z "${scriptdir}" ]]; then
    scriptdir="$(pwd)"
    read -r "userscript?Choose a directory [${scriptdir}]: "
    scriptdir="${userscript:-${scriptdir}}"
  fi

  filename="${scriptdir%/}/${1}"
  ext="${filename:e}"
  if [[ -z "${ext}" ]]; then
    ext="${default_ext}"
    filename="${filename}.${ext}"
  fi

  if [[ ! -f "${filename}" ]]; then
    case "${ext}" in
      js) print -r -- '#!/usr/bin/env node' >> "${filename}" ;;
      sh | bash) print -r -- '#!/usr/bin/env bash' >> "${filename}" ;;
      zsh) print -r -- '#!/usr/bin/env zsh' >> "${filename}" ;;
      rb) print -r -- '#!/usr/bin/env ruby' >> "${filename}" ;;
      py) print -r -- '#!/usr/bin/env python' >> "${filename}" ;;
      *) touch -- "${filename}" ;;
    esac
    print >> "${filename}"
    chmod +x "${filename}" || return
    print "\033[32;1m${filename}\033[0m"
  else
    print "\033[31;1mFile exists: ${filename}\033[0m"
  fi

  editor="${EDITOR:-vim}"
  "${editor}" "${filename}"
}

newscript "$@"
