#!/bin/bash
# --reinstall-packages-from=4.2
# need at least a user specified

NEWVERSION="$1"
CMD=""

if [ -z $1 ]; then
  about "nvm updater"
  about "* installs node to specified version and reinstalls packages from another version if specified"
  example "# updates node to latest stable and reinstalls global packages from 5.2\n\tnvmupdate node 5.2"

  echo '\n\nType a version name or node to install.\n'
  read NEWVERSION
fi

if [ -z $NEWVERSION ]; then
  echo "No version specified. Bailing."
  return;
fi

REINSTALL="$2"
source ${NVM_DIR}/nvm.sh

if [ -z $2 ]; then
  echo "If you wanna reinstall global node packages, provide the version to copy from."
  echo 'Maybe one of these (without the "v")…'
  nvm ls
  echo "\n"
  read REINSTALL
fi

if [ -z $REINSTALL ]; then
  echo "Installing version '${NEWVERSION}' without reinstalling packages"
  CMD="nvm install $NEWVERSION"
else
  echo "Installing version '${NEWVERSION}' with packages from ${REINSTALL}"
  CMD="nvm install $NEWVERSION --reinstall-packages-from=${REINSTALL}"
fi

eval $CMD
