#!/bin/bash
# --reinstall-packages-from=4.2
# need at least a user specified

NEWVERSION="$1"
CMD=""

if [ -z $1 ]; then
  echo "nvm updater"
  echo "* installs node to specified version and reinstalls packages from another version if specified\n"
  echo "Example Usage:"
  echo "\t# updates node to latest stable and reinstalls global packages from 5.2"
  echo "\t nvmupdate node 5.2"

  echo '\n\nType a version name or node to install.\n'
  read NEWVERSION
fi

if [ -z $NEWVERSION ]; then
  echo "No version specified. Bailing."
  return
fi

REINSTALL="$2"
source ${NVM_DIR}/nvm.sh

if [ -z $2 ]; then
  echo "If you wanna reinstall global node packages, provide the version to copy from."
  echo 'Maybe one of these (without the "v")…'
  nvm ls
  echo "\n"
  read REINSTALL
fi

MSG="Installing version '${NEWVERSION}' without reinstalling packages"
if [ -z $REINSTALL ]; then
  CMD="nvm install $NEWVERSION"
else
  MSG="Installing version '${NEWVERSION}' with packages from ${REINSTALL}"
  CMD="nvm install $NEWVERSION --reinstall-packages-from=${REINSTALL}"
fi

# CMD="$CMD"

echo "$MSG"
eval $CMD
