#!/usr/bin/env zsh

function shorten() {
  local width="${1:-70}"
  if [[ ! "${width}" == <-> ]]; then
    print -u2 "shorten: width must be a whole number"
    return 1
  fi
  sed -E "s/(.{${width}}).*(\\.[^.]+)?\$/\\1...\\2/"
}

shorten "$@"
