#!/usr/bin/env zsh

function slugify() {
  local text="" slug=""
  if [[ -p /dev/stdin ]]; then
    read -r text
    slug="${text}"
  elif [[ -n "${1:-}" ]]; then
    slug="${1}"
  else
    print -r -- "Type something to slugify…"
    read -r slug
  fi

  if [[ -n "${slug}" ]]; then
    print -r -- "${slug}" | iconv -c -t ascii//TRANSLIT | sed -E 's/[~^]+//g; s/[^a-zA-Z0-9]+/-/g; s/^-+|-+$//g' | tr '[:upper:]' '[:lower:]'
  fi
}

slugify "$@"
