#!/usr/bin/env zsh

function ssl-cert() {
  typeset -ri key_bits=2048
  typeset -ri cert_days=365
  openssl genrsa -out server.key "${key_bits}" || return
  openssl req -new -key server.key -out server.csr || return
  openssl x509 -req -sha256 -days "${cert_days}" -in server.csr -signkey server.key -out server.crt || return
}

ssl-cert "$@"
