#!/usr/bin/env zsh

function ssl-expires() {
  if (( $# == 0 )); then
    about 'check the expiration date of an ssl certificate'
    example 'ssl-expires foo.example.com'
    return 1
  fi
  if [[ ! "${1}" =~ '^[A-Za-z0-9.-]+$' ]]; then
    print -u2 "ssl-expires: expected a hostname"
    return 1
  fi
  echo | openssl s_client -connect "${1}:443" -servername "${1}" | openssl x509 -noout -dates
}

ssl-expires "$@"
