tap "denisidoro/tools"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "mongodb/brew"
tap "sinclairtarget/wst"
tap "wtfutil/wtfutil"
brew "ack"
brew "antigen"
brew "python", link: false
brew "awscli"
brew "bash"
brew "bat"
brew "libpng"
brew "fontconfig"
brew "cairo"
brew "composer"
brew "coreutils"
brew "couchdb"
brew "exa"
brew "exiftool"
brew "exiv2"
brew "fd"
brew "giflib"
brew "gmp"
brew "jpeg"
brew "ffmpeg"
brew "findutils"
brew "fontforge"
brew "fzf"
brew "git-extras"
brew "git-secrets"
brew "gnu-sed"
brew "gnu-tar"
brew "gnu-which"
brew "go"
brew "grep"
brew "htop"
brew "httpie"
brew "icdiff"
brew "imagemagick"
brew "lazygit"
brew "mackup"
brew "mas"
brew "mkcert"
brew "mysql@5.7", link: true
brew "ncdu"
brew "ngrep"
brew "nss"
brew "openssh"
brew "php", restart_service: true
brew "php-code-sniffer"
brew "php-cs-fixer"
brew "pipenv"
brew "pkg-config"
brew "postgresql", restart_service: true
brew "python@2"
brew "ranger"
brew "rbenv"
brew "rclone"
brew "rename"
brew "rethinkdb", restart_service: true
brew "ripgrep"
brew "rust"
brew "rustc-completion"
brew "shfmt"
brew "tree"
brew "vim"
brew "watchman"
brew "wget"
brew "wtfutil"
brew "youtube-dl"
brew "zopfli"
brew "zsh"
brew "denisidoro/tools/navi"
brew "mongodb/brew/mongodb-community"
brew "sinclairtarget/wst/um"
cask "1password"
cask "adobe-creative-cloud"
cask "adoptopenjdk"
cask "alfred"
cask "android-studio"
cask "appzapper"
cask "atom"
cask "betterzip"
cask "crunch"
cask "dash"
cask "discord"
cask "docker"
cask "dropbox"
cask "dvdstyler"
cask "edex-ui"
cask "expo-xde"
cask "firefox"
cask "flip4mac"
cask "font-iosevka"
cask "fontplop"
cask "google-chrome"
cask "gpg-suite"
cask "graphql-playground"
cask "handbrake"
cask "imagealpha"
cask "imageoptim"
cask "insomnia"
cask "integrity"
cask "iterm2"
cask "keybase"
cask "kitematic"
cask "knockknock"
cask "livereload"
cask "mark-text"
cask "mongodb-compass"
cask "namechanger"
cask "opera"
cask "overdrive-media-console"
cask "private-internet-access"
cask "psequel"
cask "quicklook-json"
cask "riot"
cask "robo-3t"
cask "screens"
cask "sequel-pro"
cask "signal"
cask "sketch"
cask "skype"
cask "slack"
cask "slate"
cask "sonos"
cask "sourcetree"
cask "suspicious-package"
cask "synologyassistant"
cask "textmate"
cask "textual"
cask "the-unarchiver"
cask "transmit"
cask "ttscoff-mmd-quicklook"
cask "vagrant"
cask "virtualbox"
cask "visual-studio-code"
cask "vlc"
cask "zeplin"
mas "Audiobook Builder", id: 1437681957
mas "AudioBookBinder", id: 413969927
mas "Citationsy", id: 1410212159
mas "Encrypto", id: 935235287
mas "Friendly Streaming", id: 553245401
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "LUCiD Exposure", id: 1133117123
mas "Mimeo Photos", id: 1282504627
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "RBdigital", id: 491365225
mas "Reeder", id: 880001334
mas "SiteSucker", id: 442168834
mas "Skitch", id: 425955336
mas "Soulver", id: 413965349
mas "Stave'n'Tabs", id: 1107712488
mas "Svgsus", id: 1106867065
mas "Xcode", id: 497799835
