tap "denisidoro/tools"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "mongodb/brew"
tap "webhookrelay/tap"
tap "wtfutil/wtfutil"
brew "ack"
brew "antigen"
brew "awscli"
brew "bash"
brew "basictex"
brew "bat"
brew "caddy"
brew "cairo"
brew "composer"
brew "coreutils"
brew "couchdb"
brew "curl"
# brew "exa"
brew "exiftool"
brew "exiv2"
brew "fd"
brew "ffmpeg"
brew "findutils"
brew "fontconfig"
brew "fontforge"
brew "fzf"
brew "gcc"
brew "gettext"
brew "giflib"
brew "git"
# brew "git-delta"
brew "git-extras"
brew "git-secrets"
brew "gnu-sed"
brew "gnu-tar"
brew "gnu-which"
brew "go"
brew "gobject-introspection"
brew "grep"
brew "htop"
brew "httpie"
brew "icdiff"
brew "icoutils"
brew "imagemagick"
brew "jpeg"
brew "jq"
# brew "lazygit"
brew "libfido2"
brew "libheif"
brew "libpng"
brew "libpq"
brew "libssh"
brew "m-cli"
brew "mackup"
brew "mas"
brew "mkcert"
brew "mongodb/brew/mongodb-community"
brew "mysql@5.7", link: true
brew "ncdu"
brew "openssh"
brew "pandoc"
brew "pandoc-citeproc"
brew "pandoc-crossref"
# brew "pango"
brew "php", restart_service: true
brew "php", restart_service: true
brew "php-code-sniffer"
brew "php-cs-fixer"
brew "pipenv"
brew "pkg-config"
brew "postgresql", restart_service: true
brew "rbenv"
brew "rclone"
brew "redis", restart_service: true
brew "rename"
brew "rethinkdb", restart_service: true
brew "ripgrep"
brew "ruby"
brew "rustc-completion"
brew "shfmt"
brew "tree"
brew "vim"
brew "webhookrelay/tap/relay"
brew "wget"
brew "wtfutil"
brew "yadm"
brew "youtube-dl"
brew "zopfli"
brew "zsh"
cask "alfred"
cask "appzapper"
cask "betterzip"
cask "brave-browser"
cask "crunch"
cask "discord"
cask "docker"
cask "figma"
cask "firefox"
cask "font-iosevka"
cask "fontgoggles"
cask "fontplop"
cask "google-chrome"
cask "handbrake"
cask "imagealpha"
cask "imageoptim"
cask "insomnia"
cask "iterm2"
# cask "karabiner-elements"
cask "keybase"
# cask "kitematic"
cask "knockknock"
cask "lastpass"
# cask "livereload"
cask "menumeters"
cask "microsoft-auto-update"
cask "microsoft-edge"
cask "microsoft-teams"
cask "mongodb-compass"
cask "namechanger"
cask "notion"
cask "opera"
# cask "oracle-jdk"
cask "postman"
cask "private-internet-access"
# cask "psequel"
cask "robo-3t"
# cask "screens"
# cask "sequel-pro"
# cask "signal"
# cask "skype"
cask "sonos"
cask "sourcetree"
cask "ssh-tunnel-manager"
cask "textmate"
# cask "textual"
cask "the-unarchiver"
cask "transmit"
cask "vagrant"
cask "virtualbox"
cask "visual-studio-code"
cask "vlc"
cask "webpquicklook"
cask "zettlr"
mas "1Password 7", id: 1333542190
mas "Acorn", id: 1547371478
mas "Affinity Designer", id: 824171161
# mas "Audiobook Builder", id: 1437681957
# mas "AudioBookBinder", id: 413969927
# mas "GarageBand", id: 682658836
# mas "iMovie", id: 408981434
# mas "Keynote", id: 409183694
# mas "Mimeo Photos", id: 1282504627
mas "Next Meeting", id: 1017470484
# mas "Numbers", id: 409203825
# mas "Pages", id: 409201541
mas "Reeder", id: 880001334
mas "Slack", id: 803453959
mas "Soulver 2", id: 413965349
mas "Svgsus", id: 1106867065
# mas "Xcode", id: 497799835
