#!/bin/sh

if [ $1 = 0000000000000000000000000000000000000000 ]; then
  old=4b825dc642cb6eb9a060e54bf8d69288fbee4904
else
  old=$1
fi

red=`tput setaf 1`
yellow=`tput setaf 3`
reset=`tput sgr0`
div="\n${yellow}******************${reset}\n"


# Warn if Gemfile updated remotely
if [ -f Gemfile ] && command -v bundle >/dev/null &&
  git diff --name-only $old $2 | egrep -q '^Gemfile|\.gemspec$'
then
  msg="${red}YOUR RUBY BUNDLES COULD BE OUT OF DATE. RUN \"bundle install\".${reset}"
  (echo ${div}${msg}${div})
  # (unset GIT_DIR; exec bundle check || exec bundle install)
  true
fi

# Do the same for composer.lock
if [ -f composer.lock ] && command -V composer >/dev/null &&
  git diff --name-only $old $2 | egrep -q '^composer\.lock$'
then
  msg="${red}YOUR COMPOSER PACKAGES COULD BE OUT OF DATE. RUN \"composer install\".${reset}"
  (echo ${div}${msg}${div})
  # (exec composer install)
  true
fi

# And same for package.json
node_msg="${red}YOUR NODE MODULES COULD BE OUT OF DATE. RUN ${reset}"

if [ -f yarn.lock ] && [ -f package.json ] &&
  command yarn help >/dev/null &&
  git diff --name-only $old $2 | egrep -q '^package\.json$'
then
  msg="${yellow}\"yarn install\".${reset}"
  (echo ${div}${node_msg}${msg}${div})
  true
elif [ -f package.json ] && command -v npm >/dev/null &&
  git diff --name-only $old $2 | egrep -q '^package\.json$'
then
  msg="${yellow}\"npm install\".${reset}"
  (echo ${div}${node_msg}${msg}${div})
  true
fi
