---
- name: Install GitLab Runner (Debian)
  import_tasks: install-debian.yml
  when: ansible_os_family == 'Debian'

- name: Install GitLab Runner (RedHat)
  import_tasks: install-redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Set global options
  import_tasks: global-setup.yml

- name: Register GitLab Runner
  import_tasks: register-runner.yml
  when: gitlab_runner_registration_token != ''
