---
dependencies: []

galaxy_info:
  author: pmbauer
  description: role for operating tarsnap backups
  company: "N/A"
  license: "GPL v3"
  min_ansible_version: 1.7
  platforms:
  - name: Debian
    versions:
    - wheezy
  - name: Ubuntu
    versions:
    - precise
    - trusty
  categories:
    - cloud
    - system
