---

- name: Compatibility check
  fail: msg="This role only works on Debian systems"
  when: not ansible_os_family == "Debian"

- include: install.yml
  tags:
    - networking
    - ufw
    - ufw-install

- include: reset.yml
  tags:
    - networking
    - ufw
    - ufw-reset

- include: config.yml
  tags:
    - networking
    - ufw
    - ufw-config

- include: service.yml
  tags:
    - networking
    - ufw
    - ufw-service
